project_name: mould
release:
  github:
    owner: dihedron
    name: mason
  name_template: '{{.Tag}}'
scoop:
  name: mason
  commit_author:
    name: Andrea Funtò
    email: dihedron.dev@gmail.com
  commit_msg_template: Scoop update for {{ .ProjectName }} version {{ .Tag }}
before:
  hooks:
#    - make clean
    - go mod tidy
    - go generate ./...    
builds:
  - env: 
    - DESCRIPTION=Template engine to generate documents based on input data.
    - COPYRIGHT=2022-2023 © Andrea Funtò
    - LICENSE=MIT
    - LICENSE_URL=https://opensource.org/licenses/MIT
    - GOVERSION=1.21.1
    # - GOVERSION=$(go version | awk '{print $3;}')
    - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    flags:
      - -v
    ldflags:
      - -X 'github.com/dihedron/mason/build.Name={{.ProjectName}}'
      - -X 'github.com/dihedron/mason/build.Description={{.Env.DESCRIPTION}}'
      - -X 'github.com/dihedron/mason/build.Copyright={{.Env.COPYRIGHT}}' 
      - -X 'github.com/dihedron/mason/build.License={{.Env.LICENSE}}' 
      - -X 'github.com/dihedron/mason/build.LicenseURL={{.Env.LICENSE_URL}}' 
      - -X 'github.com/dihedron/mason/build.GoVersion={{.Env.GOVERSION}}' 
      - -X 'github.com/dihedron/mason/build.GoOS={{.Os}}' 
      - -X 'github.com/dihedron/mason/build.GoArch={{.Arch}}' 
      - -X 'github.com/dihedron/mason/build.GitTag={{.Tag}}' 
      - -X 'github.com/dihedron/mason/build.GitCommit={{.ShortCommit}}' 
      - -X 'github.com/dihedron/mason/build.GitHash={{.FullCommit}}' 
      - -X 'github.com/dihedron/mason/build.BuildDate={{.Date}}' 
      - -X 'github.com/dihedron/mason/build.BuildTime={{.Timestamp}}' 
      - -X 'github.com/dihedron/mason/build.VersionMajor={{.Major}}' 
      - -X 'github.com/dihedron/mason/build.VersionMinor={{.Minor}}' 
      - -X 'github.com/dihedron/mason/build.VersionPatch={{.Patch}}' 
    hooks:
    #   pre: <whatever>
      # post: 
      #   - upx --best "{{.Path}}"
dockers:
- image_templates: ["ghcr.io/goreleaser/example:{{ .Version }}"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/dihedron/mason
  - --label=org.opencontainers.image.source=https://github.com/dihedron/mason
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
nfpms:
- maintainer: Andrea Funtò <dihedron dot dev at gmail dot com>
  description: Template engine to generate documents based on input data.
  homepage: https://github.com/caarlos0/tasktimer
  license: MIT
  formats:
  - deb
  - rpm
  - apk
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
# gomod:
#   proxy: false
#   env:
#     - GOPROXY=https://proxy.golang.org,direct
#     - GOSUMDB=sum.golang.org
#     - GOPRIVATE=example.com/blah
#  gobinary: go




