project_name: mason
before:
  hooks:
    - make clean
    - go mod tidy
    - go generate ./...    
builds:
  - env: 
    - DESCRIPTION=Build tools and helpers collection.
    - COPYRIGHT=2022 © Andrea Funtò
    - LICENSE=MIT
    - LICENSE_URL=https://opensource.org/licenses/MIT
    - GOVERSION=1.17.5
    # - GOVERSION=$(go version | awk '{print $3;}')
    - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    flags:
      - -v
    ldflags:
      - -X 'git.gld-1.cloud.bankit.it/shared/utils/cloudctl/sdk/build.Name={{.ProjectName}}'
      - -X 'git.gld-1.cloud.bankit.it/shared/utils/cloudctl/sdk/build.Description={{.Env.DESCRIPTION}}'
      - -X 'git.gld-1.cloud.bankit.it/shared/utils/cloudctl/sdk/build.Copyright={{.Env.COPYRIGHT}}' 
      - -X 'git.gld-1.cloud.bankit.it/shared/utils/cloudctl/sdk/build.License={{.Env.LICENSE}}' 
      - -X 'git.gld-1.cloud.bankit.it/shared/utils/cloudctl/sdk/build.LicenseURL={{.Env.LICENSE_URL}}' 
      - -X 'git.gld-1.cloud.bankit.it/shared/utils/cloudctl/sdk/build.GoVersion={{.Env.GOVERSION}}' 
      - -X 'git.gld-1.cloud.bankit.it/shared/utils/cloudctl/sdk/build.GoOS={{.Os}}' 
      - -X 'git.gld-1.cloud.bankit.it/shared/utils/cloudctl/sdk/build.GoArch={{.Arch}}' 
      - -X 'git.gld-1.cloud.bankit.it/shared/utils/cloudctl/sdk/build.GitTag={{.Tag}}' 
      - -X 'git.gld-1.cloud.bankit.it/shared/utils/cloudctl/sdk/build.GitCommit={{.ShortCommit}}' 
      - -X 'git.gld-1.cloud.bankit.it/shared/utils/cloudctl/sdk/build.GitHash={{.FullCommit}}' 
      - -X 'git.gld-1.cloud.bankit.it/shared/utils/cloudctl/sdk/build.BuildDate={{.Date}}' 
      - -X 'git.gld-1.cloud.bankit.it/shared/utils/cloudctl/sdk/build.BuildTime={{.Timestamp}}' 
      - -X 'git.gld-1.cloud.bankit.it/shared/utils/cloudctl/sdk/build.VersionMajor={{.Major}}' 
      - -X 'git.gld-1.cloud.bankit.it/shared/utils/cloudctl/sdk/build.VersionMinor={{.Minor}}' 
      - -X 'git.gld-1.cloud.bankit.it/shared/utils/cloudctl/sdk/build.VersionPatch={{.Patch}}' 
    hooks:
  #   pre: <whatever>
      post: 
        - upx --best "{{.Path}}"
dockers:
- image_templates: ["ghcr.io/goreleaser/example:{{ .Version }}"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/goreleaser/example
  - --label=org.opencontainers.image.source=https://github.com/goreleaser/example
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
nfpms:
- maintainer: Andrea Funtò <dihedron dot dev at gmail dot com>
  description: Build tools and helpers collection.
  homepage: https://github.com/caarlos0/tasktimer
  license: MIT
  formats:
  - deb
  - rpm
  - apk
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
# gomod:
#   proxy: false
#   env:
#     - GOPROXY=https://proxy.golang.org,direct
#     - GOSUMDB=sum.golang.org
#     - GOPRIVATE=example.com/blah
#  gobinary: go




